spring:
  application:
    name: auth-service
server:
  port: 9100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
services:
  rest:
    data-service:
      getUser:
        url: http://localhost:9091/findUserByUsername?username=
      addUser:
        url: http://localhost:9091/addUser